#pragma once
enum SimulationFlag {
  ALLOW_ALL = 0,
  DISALLOW_BLOCKED_SMALL_OBSTACLE = 1,
  DISALLOW_BLOCKED_LARGE_OBSTACLE = 2,
  DISALLOW_FAILURE = 4,
  DISALLOW_FREEWHEELING = 8,
  DISALLOW_SINKING = 16
};
