enum class WheelCommand : int { 
  NONE = 00,
  ALL_FORWARDS = 01,
  ALL_BACKWARDS = 02,
  ALL_CLOCKWISE = 03,
  ALL_COUNTER_CLOCK_WISE = 04,
  
  FRONT_LEFT_NONE = 10,
  FRONT_LEFT_FORWARDS = 11,
  FRONT_LEFT_BACKWARDS = 12,
  FRONT_LEFT_CLOCK_WISE = 13,
  FRONT_LEFT_COUNTER_CLOCK_WISE = 14,
  
  FRONT_RIGHT_NONE = 20,
  FRONT_RIGHT_FORWARDS = 21,
  FRONT_RIGHT_BACKWARDS = 22,
  FRONT_RIGHT_CLOCK_WISE = 23,
  FRONT_RIGHT_COUNTER_CLOCK_WISE = 24,
  
  MIDDLE_LEFT_NONE = 30,
  MIDDLE_LEFT_FORWARDS = 31,
  MIDDLE_LEFT_BACKWARDS = 32,
  
  MIDDLE_RIGHT_NONE = 40,
  MIDDLE_RIGHT_FORWARDS = 41,
  MIDDLE_RIGHT_BACKWARDS = 42,
  
  BACK_LEFT_NONE = 50,
  BACK_LEFT_FORWARDS = 51,
  BACK_LEFT_BACKWARDS = 52,
  BACK_LEFT_CLOCK_WISE = 53,
  BACK_LEFT_COUNTER_CLOCK_WISE = 54,
  
  BACK_RIGHT_NONE = 60,
  BACK_RIGHT_FORWARDS = 61,
  BACK_RIGHT_BACKWARDS = 62,
  BACK_RIGHT_CLOCK_WISE = 63,
  BACK_RIGHT_COUNTER_CLOCK_WISE = 64
};
